# Generated by Django 5.2.10 on 2026-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('stressed', 'Stressed'), ('chill', 'Chill')], default='happy', max_length=20),
        ),
    ]
