# Generated by Django 5.2.10 on 2026-01-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='Chennai', max_length=100),
        ),
    ]
